### ISSUE TITLE
Add instructions for compilation

### ISSUE THREAD

**Issue by himanshupal** [aryannewyork/Assembly-Code_ARM-SIM#1]
Currently the repository is missing the instructions for compilation, description of the type of assembly used here. Can you provide some instructions or add them to README on how to get things working? Thanks

**Comment by aryanshukla7** [comment]
Thankyou for reviewing the repository, I actually uploaded it a couple days ago, and I am yet to document the code. I will soon do it. But in the meantime, you can try to run it using ARM SIM, https://webhome.cs.uvic.ca/~nigelh/ARMSim-V2.1/index.html

**Comment by himanshupal** [comment]
Got it!

**Comment by aryanshukla7** [comment]
Hello @himanshupal 
I have now completed the documentation and you can refer to it in case you had any trouble running and understanding the code
